name: ğŸ“¦ Build kotlin
run-name: ğŸ“¦ï¸ Build kotlin - ${{ github.event.repository.name }} by @${{ github.actor }}
on:
  workflow_call:
jobs:
  build-kotlin:
    steps:
      - name: â¬‡ï¸ Checks-out code
        uses: actions/checkout@v3
