name: ğŸ“¦ Reusable
run-name: ğŸ“¦ï¸ Reusable kotlin - ${{ github.event.repository.name }} by @${{ github.actor }}
on:
  workflow_call:
jobs:
  reusable:
    name: Reusable
    runs-on: ubuntu-22.04
    steps:
      - name: â¬‡ï¸ Checks-out code
        uses: actions/checkout@v3
