name: â­ Create release
on:
  push:
jobs:
  create-release-candidate:
    name: ğŸ“¦ï¸ Create release candidate
    steps:
      - name: â„¹ï¸ Print
        run: echo "::notice::ğŸ“¦ï¸ Release candidate created"
  deploy-release-candidate:
    name: ğŸš€ï¸ Deploy release candidate
    steps:
      - name: â„¹ï¸ Print
        run: echo "::notice::ğŸš€ï¸ Release candidate deployed"
  promote-release:
    name: ğŸ“¦ï¸ Promote release
    environment: validate
    steps:
      - name: â„¹ï¸ Print
        run: echo "::notice::ğŸ“¦ï¸ï¸ Release promoted"
